### ISSUE TITLE
Use Actual Related List Labels

### ISSUE THREAD

**Issue by douglascayers** [douglascayers/sfdc-related-files-lightning#1]
Due to limitation in Apex, the SObject Describe info only provides the API name of child relationships or the label of an object, **not** the label of the child relationship.

See this [StackExchange post](https://salesforce.stackexchange.com/questions/9140/access-the-related-list-label-for-a-lookup-relationship?stw=2) about the limitation.

This means if we have an object `Foo__c` with two lookup fields to object `Bar__c` and each lookup field assigned different related list labels like "Mars Bars" and "Candy Bars" then Apex code isn't able to determine those labels. Instead, Apex SObject Describe info can tells us the API names like `Mars_Bars__r` and `Candy_Bars__r` or the labels of the `Bar__c` object itself: "Bar" (singular label) and "Bars" (plural label).

For now, the app displays the **plural label** of the object the lookup field points to. It's not ideal, but better than nothing. If you mouse over the relationship name in the vertical navigation then the tooltip that displays includes the API name of the child relationship.

This means that if a child object has multiple lookup fields to the same parent object then the **Related Files** lightning component will display the parent object's **plural label** multiple times too.

![image](https://user-images.githubusercontent.com/4142577/29747024-4baeae86-8ab2-11e7-90e6-d60271f90e4d.png)

Cory Cowgill [suggests](https://twitter.com/corycowgill/status/901086706073567233) trying to use the [User Interface API](https://developer.salesforce.com/docs/atlas.en-us.uiapi.meta/uiapi/ui_api_responses_child_relationship.htm#ui_api_responses_child_relationship) but I fear it may have same limitation as Apex.

**Comment by DouglasCAyers** [comment]
I am of the opinion this is impossible to determine dynamically.

* The Apex SObject Describe certainly does not provide the child relationship labels, only API names.
* The User Interface API only provides what Apex Describe provides.
* The Metadata API, although provides info about Related Lists in Layouts, neither provides the expected API name and does not provide any labels either.

**Comment by DouglasCAyers** [comment]
According to forward-looking statement by [Kamyar Seradjfar](https://success.salesforce.com/0D53A00003Dwz1g), Salesforce is working on a Lists API that would provide more metadata information about related lists. It's yet to be seen whether this new API will provide the related list label, but one can be hopeful.

**Comment by douglascayers** [comment]
Through a combination of Tooling API and Apex SObject Describe info, I've been able to determine either the related list labels, or very nearly close to it, for both standard and custom fields.

![image](https://user-images.githubusercontent.com/4142577/57989609-d0cd2600-7a62-11e9-8fdb-f3c486cd84dc.png)

For standard fields, I use the **Custom Relationship Name**:
![image](https://user-images.githubusercontent.com/4142577/57989618-fce8a700-7a62-11e9-9a4c-4a60ecab2a93.png)

For custom fields, I use Tooling API:
![image](https://user-images.githubusercontent.com/4142577/57989643-5e107a80-7a63-11e9-8fc0-886a80bee3e8.png)

Oddly, unfortunately, frustratingly, the way to determine the related list labels is different for standard and custom fields so the solution is a more complex than I'd like, but it works.
