### ISSUE TITLE
Possible to add more columns and change sorting?

### ISSUE THREAD

**Issue by jonlarosa** [douglascayers/sfdc-related-files-lightning#11]
Hi Doug,
Thanks so much for this tool, really a lifesaver for some of my clients.
Is it possible (or on the roadmap) to add the ability to add more columns in addition to the defaults (Title, Owner, Last Modified, Size)?
Similarly, it seems like the sorting is by Last Modified. Is it possible to sort the list by a different column?
Thanks again,
Jon LaRosa

**Comment by DouglasCAyers** [comment]
Hi @jonlarosa,

Thanks for the kind feedback and feature suggestions!

I've thought about making the columns configurable, ideally wanted to use FieldSets but they aren't supported (or I didn't see how) for Files. Maybe we'll have to go with comma delimited list of field API names like we are for which related lists to show.

I have not introduced sorting yet, but with the new `<lightning:datatable>` component in Winter '18 release maybe this will be easier to implement.

Thanks,

Doug

**Comment by DouglasCAyers** [comment]
Update, *Field Sets* do exist in the Classic Setup for Content Version object but are not being displayed in Object Manager in Lightning Experience -- so I thought Field Sets weren't available. Will make sure to loop back on this to allow columns to be customized by field sets and sorting.

**Comment by DouglasCAyers** [comment]
Hi @jonlarosa, 

In Winter '18, the `lightning:datatable` component is not robust enough. The [Spring '18 release](https://releasenotes.docs.salesforce.com/en-us/spring18/release-notes/rn_lc_components.htm) shows much more promise.

In the develop branch I've already added support for field sets, but won't be part of the managed package until Spring '18. In fact, I can't create any new managed package versions until Spring '18 due to this [known issue](https://success.salesforce.com/issues_view?id=a1p3A000000EQJzQAO).

Thanks

**Comment by douglascayers** [comment]
The [lightning:datatable](https://developer.salesforce.com/docs/component-library/bundle/lightning:datatable/example) component has matured enough to begin working on this enhancement request.

**Comment by douglascayers** [comment]
I'm going to split this issue into two parts:

* Ability to customize displayed fields (by using a Field Set on Content Version object)
* Ability to sort the data table

I've gotten the field set support done, but it'll take a bit before the sorting support is ready, so I don't want to potentially hold up the entire release if I don't get to the sorting bit yet.

**Comment by douglascayers** [comment]
Thank you for the feedback. In [Release 1.2](https://github.com/douglascayers/sfdc-related-files-lightning#packaged-release-history), you can now customize the displayed columns by creating a field set on the Content Version object then selecting the field set for the Related Files component in app builder.

![image](https://user-images.githubusercontent.com/4142577/57998444-2de2cf00-7a97-11e9-994e-b041b57c2931.png)

![image](https://user-images.githubusercontent.com/4142577/57998492-58cd2300-7a97-11e9-8a8d-ac851475ec60.png)
