### ISSUE TITLE
Fatal Component Error

### ISSUE THREAD

**Issue by steinstv** [douglascayers/sfdc-related-files-lightning#15]
Hello @DouglasCAyers 
Setup:
I have the Related Files component included on the Account page layout
Component is configured to display the Email child relationship
Enhanced Email is enabled for the org
I am using Lightning for Outlook to upload email attachments from Outlook to an Account record

Repro: 
From the Lightning for Outlook side panel, upload an email with attachments to an Account.  
* Email is attached to Account as a completed activity and File is correctly related to Activity
* Email category on Related Files component correctly displays the list of uploaded files
* Clicking on any of the uploaded File names throws a fatal Component Error message with the attached details
![relatedfiles_emailmessagelisting](https://user-images.githubusercontent.com/34343751/38335002-cdc57fdc-3811-11e8-881d-62c0a52874c8.JPG)
![relatedfiles_componenterror](https://user-images.githubusercontent.com/34343751/38334842-5edbd922-3811-11e8-899b-a6315e224e6b.JPG)
[RelatedFiles_ComponentStackTrace.txt](https://github.com/DouglasCAyers/sfdc-related-files-lightning/files/1877669/RelatedFiles_ComponentStackTrace.txt)

**Comment by DouglasCAyers** [comment]
Hi @steinstv,

Thank you for the detailed information and steps to reproduce. I don't have Outlook so I can't try the Lightning for Outlook steps exactly like you. I did test by sending an email with an attachment from an Account record. Everything worked fine in that scenario, I can click on the files in the "Email Messages" category and the file previews appear.

Are you still getting errors? Do you only get the error in that specific way of using Lightning for Outlook or do you get errors on other files uploaded via Salesforce UI?

Thanks

**Comment by douglascayers** [comment]
I'm closing this issue due to no response and I'm unable to reproduce. If you're still encountering the issue, please comment back and I'll re-open. Thanks
