### ISSUE TITLE
Duplicate Objects listed in the Side Bar

### ISSUE THREAD

**Issue by ericrsmith35** [douglascayers/sfdc-related-files-lightning#16]
When using this component on Account, I am getting duplicate selections for objects on the sidebar.
![image](https://user-images.githubusercontent.com/24724447/44636384-77bfde00-a979-11e8-9ba8-af8a6edb1359.png)

**Comment by douglascayers** [comment]
Hi @ericrsmith35,

Thanks for checking out my project! What you're seeing are not actually duplicates, those are actual related lists, but their labels are only the label of the object so it appears as if they are duplicates. This is a known issue as reported here https://github.com/DouglasCAyers/sfdc-related-files-lightning/issues/1

This is a system limitation as far as I can tell, the Salesforce API just doesn't expose enough information at the moment. =(
