### ISSUE TITLE
Showing Local Record Files

### ISSUE THREAD

**Issue by JordanGrubb22** [douglascayers/sfdc-related-files-lightning#18]
Hi,

I was wondering how to show the files for the current record you are on, I use this app for showing all files in any Service appointment under the work order, this works great but id love it if I could show both service appointment files and work order but when I enter work order under Child relationships it doesn't show. I know this isn't a child relation but when no filters are in this field it does show so they must be a way? 

Thank you.

**Comment by douglascayers** [comment]
Hi @JordanGrubb22, to show files that belong to the current record being viewed, please use the standard **Files** related list. This app only shows files related to child records. Thanks!
