### ISSUE TITLE
unable to relate attachments from emails

### ISSUE THREAD

**Issue by leahwils** [douglascayers/sfdc-related-files-lightning#19]
@douglascayers Hi Doug, awesome plug in except for one little issue.  Im trying to pull in attachments from emails, however, when i include Emails to the Child relationships, nothing is populating.  Since these emails show up in the activity history, i've tried to pull in 'activities' into the child relationships but the lightning page builder just keeps spinning and wont complete.  

These emails were attached through the SF for Outlook plug in and would originally have been related to that contact.  

Not sure what i'm doing wrong so any assistance would be appreciated!

**Comment by leahwils** [comment]
Also, i have opportunities that have several attachments that are not showing up.

**Comment by douglascayers** [comment]
Hi @leahwils, I see you're using the word "attachments" and I just want to make sure we're using the same terminology.

In Salesforce, there are two related lists you can use to upload documents, images, etc. to your records: **Attachments** and **Files**. The "old" way was attachments via the "Notes & Attachments" related list and the "new" way is via the "Files" related list.

This Lightning component only works with **Files** (whose object api name is ContentVersion). It won't display anything that was saved in the Attachment object.

To learn more about converting "Notes & Attachments" to the newer "Files" and "Notes" related lists, please see [my blog post and Dreamforce presentations](https://douglascayers.com/adopting-files-and-enhanced-notes-in-lightning-experience/).

Thanks
