### ISSUE TITLE
Opportunities not working on Contacts

### ISSUE THREAD

**Issue by BAebischer** [douglascayers/sfdc-related-files-lightning#20]
Hi Douglas, 
First of all a big big thank you for this great solution. I just installed the related files component and on the account everything is working as expected - I only want the files for cases, opportunities and contacts showing up and it works. I tried to add the component to the contact object and experience the following issue: When I don't define any specific child relationship, then opportunities files are showing. However, as soon as I specify the child relationship to opportunities its not working and I get the following error:
"Sorry, error initializing component"- what I'm missing here?

Thank you in advance for your help!

Best regards, 
Benjamin

**Comment by BAebischer** [comment]
Just found the answer - I needed to indicate the child relationship for opportunities as "opportunities__r" and it worked

**Comment by douglascayers** [comment]
@BAebischer yep, the relationship values need to be the unique API or Developer names. Glad you got it worked out
