### ISSUE TITLE
Recent Error - "Sorry, error initializing component"

### ISSUE THREAD

**Issue by leahwils** [douglascayers/sfdc-related-files-lightning#24]
what would prompt this error all of a sudden?  it has been working fine, and then today in my sandbox i get this error whenever i navigate to this component.  I am trying to view files on related records such as oppty's and contracts.  This has been working great until...well not sure exactly but i checked it today and its giving me that error whenever i open that component.  It worked last week, that much i know, and i've not made any configuration changes recently.  
Any thoughts @douglascayers ?

**Comment by leahwils** [comment]
this appears to have resolved itself

**Comment by douglascayers** [comment]
Thanks for the update, @leahwils. Glad it's resolved. Any chance your sandbox recently updated to Summer '19 release? Since it's working now, may not be any need to put more thought into it.

**Comment by leahwils** [comment]
No, we arent scheduled for that until June 15.  It was super random - like
it was just stalling out.

Thanks for responding though!

**Comment by rlankathil** [comment]
@douglascayers We are having the same issue in some of our profiles. This issue happens when the profile does not contain "see all data" access and record having a large amount of file (around 250 attachments). I think this issue should be re-open.
