### ISSUE TITLE
Question - take it one level up - to the account

### ISSUE THREAD

**Issue by leeBringg** [DouglasCAyers/sfdc-related-files-lightning#3]
Hi Douglas,

By my understanding, the files we see in the parent object is by the related to field in the task object.

Is it possible to take it one level up, so we will be able to see every thing under the account level?

For example:
Task that related to opportunity, will be seen in the related account of the opportunity.

Thanks, Lee.

**Comment by DouglasCAyers** [comment]
For tasks/events/activities, I believe this could be simple to add in for records that use the standard WhatId and WhoId and then the Task.AccountId will be populated. 

For the fix yesterday in issue #2 for querying on custom lookup fields this will be trickier. Not sure if the AccountId gets populated or not. 

I'll take a look, thanks for the suggestion!

**Comment by leeBringg** [comment]
Hi Douglas,

Yes, I'm talking about standard salesforce object that related to tasks and extract files to the account level from them:
Opportunity.AccountId, Contact.AccountId...

Thanks, Lee
