### ISSUE TITLE
Not loading in Production

### ISSUE THREAD

**Issue by JoyAnnFisher** [DouglasCAyers/sfdc-related-files-lightning#4]
Hi Doug! I installed this in both my Sandbox and Production instances yesterday and the latter is not working today - it just keeps spinning on load. It is still working in the Sandbox however. Any ideas or troubleshooting steps?

Thank you!

**Comment by JoyAnnFisher** [comment]
This was an error on my part! Something I was experimenting in yesterday that I did not undo. Sorry!

**Comment by DouglasCAyers** [comment]
Glad you figured it out!

Please let me know any feedback you think would make this a better tool or if you run into any other issues. 

Thanks!
